version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: chat-nginx
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/.composer:/root/.composer
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    container_name: chat-php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: chat-mysql
    restart: always
    ports:
      - '3000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: chat
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
    volumes:
      - /var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

